### PR TITLE
Prevent boost 1.72 in conda

### PR DESCRIPTION
**Pull request by Besler**
Should fix https://github.com/Bonelab/Bonelab/issues/18.

In the future, we can update to 1.72. We will need to modify CMakeLists.txt as well.

### CODE REVIEW

**Comment by Besler** [comment]
We will need to fix this package on conda. Let's not make a new version (since we only modified conda) and just swap the files. We can delete the packages on anaconda and then re-upload.

We should make the same change to all C++ source code: n88util, pQCTIO.

@stevenkboyd Do you want the "learning experience" or should I just go ahead?

**Comment by Besler** [comment]
Hi Steve,

if you look at the change I made in this pull request (one line) you can do the same w/ n88util and pqctio. Once merged to master and build successful, do the process to upload to anaconda as before (for n88util, aimio, and pqctio - no need to do vtkbone/n88tools).

https://github.com/Numerics88/n88util/wiki/Azure,-Conda,-and-all-that

Bryce

**Comment by stevenkboyd** [comment]
I think I’ve submitted the pull requests now correctly. Shall I accept them or is it better for you or another person to accept and then build the conda libraries again. Steve

--
Steven Boyd
PhD, Professor, University of Calgary
Director, McCaig Institute for Bone and Joint Health
Full Signature<https://ucalgary.ca/people/steven-boyd/contact>

On Apr 8, 2021, at 3:14 PM, Bryce Besler ***@***.******@***.***>> wrote:

[△EXTERNAL]




Hi Steve,

if you look at the change I made in this pull request (one line) you can do the same w/ n88util and pqctio. Once merged to master and build successful, do the process to upload to anaconda as before (for n88util, aimio, and pqctio - no need to do vtkbone/n88tools).

https://github.com/Numerics88/n88util/wiki/Azure,-Conda,-and-all-that

Bryce

**Comment by Besler** [comment]
Yes, these looks good! I can see the artifacts: https://dev.azure.com/babesler/n88/_build/results?buildId=1347&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by stevenkboyd** [comment]
Now that the changes for pQCTIO and n88util are also merged, do we need to build new artifacts before uploading?
--
Steven Boyd
PhD, Professor, University of Calgary
Director, McCaig Institute for Bone and Joint Health
Full Signature<https://ucalgary.ca/people/steven-boyd/contact>

On Apr 9, 2021, at 11:15 AM, Bryce Besler ***@***.******@***.***>> wrote:

[△EXTERNAL]




Yes, these looks good! I can see the artifacts: https://dev.azure.com/babesler/n88/_build/results?buildId=1347&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by Besler** [comment]
Once you merge into master, the artifacts will be built automatically. Find them, upload them is all.

**Comment by stevenkboyd** [comment]
Ok, I was just surprised I didn’t get a message from Azure saying the builds had happened again. I’ll look at the Azure page.


--
Steven Boyd
PhD, Professor, University of Calgary
Director, McCaig Institute for Bone and Joint Health
Full Signature<https://ucalgary.ca/people/steven-boyd/contact>

On Apr 9, 2021, at 12:16 PM, Bryce Besler ***@***.******@***.***>> wrote:

[△EXTERNAL]




Once you merge into master, the artifacts will be built automatically. Find them, upload them is all.

**Pull request merged**
